apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web-ingress
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - http:
      paths:
      {{- range .Values.routes }}
      - backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .servicePort }}
        path: {{ .path }}
        pathType: Prefix
      {{- end }}